CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  email varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description varchar,
  available boolean,
  owner_id bigint REFERENCES users ON DELETE CASCADE,
  request_id bigint
);