CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  email varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  description varchar,
  available boolean NOT NULL,
  owner_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
  request_id bigint
);

CREATE TABLE IF NOT EXISTS bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id bigint NOT NULL REFERENCES items ON DELETE CASCADE,
  booker_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
  status varchar NOT NULL,
  start_date timestamp NOT NULL,
  end_date timestamp NOT NULL,
  request_id bigint
);

CREATE TABLE IF NOT EXISTS comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text NOT NULL,
  item_id bigint NOT NULL REFERENCES items ON DELETE CASCADE,
  author_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
  created timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS item_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text NOT NULL,
  requester_id bigint NOT NULL REFERENCES users ON DELETE CASCADE,
  created timestamp NOT NULL
);